src/main/java/kafdrop/model/ConsumerPartitionVO.java
/*
 * Copyright 2017 Kafdrop contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package kafdrop.model;

public final class ConsumerPartitionVO {
  private final String groupId;
  private final String topic;
  private final int partitionId;
  private long offset;
  private long size;
  private long firstOffset;

  public ConsumerPartitionVO(String groupId, String topic, int partitionId) {
    this.groupId = groupId;
    this.topic = topic;
    this.partitionId = partitionId;
  }

  public String getTopic() {
    return topic;
  }

  public int getPartitionId() {
    return partitionId;
  }

  public long getSize() {
    return size;
  }

  public void setSize(long size) {
    this.size = size;
  }

  public long getFirstOffset() {
    return firstOffset;
  }

  public void setFirstOffset(long firstOffset) {
    this.firstOffset = firstOffset;
  }

  public long getLag() {
    if (size < 0 || firstOffset < 0) {
      return 0;
    } else if (offset < firstOffset) {
      return size - firstOffset;
    } else {
      return size - offset;
    }
  }

  public long getOffset() {
    return offset;
  }

  public void setOffset(long offset) {
    this.offset = offset;
  }

  @Override
  public String toString() {
    return ConsumerPartitionVO.class.getSimpleName() + " [groupId=" + groupId +
        ", topic=" + topic + ", partitionId=" + partitionId + ", offset=" + offset +
        ", size=" + size + ", firstOffset=" + firstOffset + "]";
  }
}

src/main/java/kafdrop/model/MessageVO.java
/*
 * Copyright 2017 Kafdrop contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package kafdrop.model;

import java.util.*;
import java.util.stream.*;

public final class MessageVO {
  private int partition;
  private long offset;
  private String message;
  private String key;
  private Map<String, String> headers;
  private Date timestamp;

  public int getPartition() { return partition; }
  public void setPartition(int partition) { this.partition = partition; }

  public long getOffset() { return offset; }
  public void setOffset(long offset) { this.offset = offset; }

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public Map<String, String> getHeaders() {
    return headers;
  }

  public void setHeaders(Map<String, String> headers) {
    this.headers = headers;
  }

  public String getHeadersFormatted() {
    if (headers.isEmpty()) {
      return "empty";
    } else {
      return headers.entrySet().stream()
          .map(e -> e.getKey() + ": " + e.getValue())
          .collect(Collectors.joining(", "));
    }
  }

  public Date getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }
}

src/main/java/kafdrop/model/TopicVO.java
/*
 * Copyright 2017 Kafdrop contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package kafdrop.model;

import java.util.*;
import java.util.stream.*;

public final class TopicVO implements Comparable<TopicVO> {
  private final String name;

  private Map<Integer, TopicPartitionVO> partitions = new TreeMap<>();

  private Map<String, String> config = Collections.emptyMap();

  public TopicVO(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }

  public Map<String, String> getConfig() {
    return config;
  }

  public void setConfig(Map<String, String> config) {
    this.config = config;
  }

  public Map<Integer, TopicPartitionVO> getPartitionMap() {
    return Collections.unmodifiableMap(partitions);
  }

  public Collection<TopicPartitionVO> getPartitions() {
    return Collections.unmodifiableCollection(partitions.values());
  }

  public void setPartitions(Map<Integer, TopicPartitionVO> partitions) {
    this.partitions = partitions;
  }

  public Optional<TopicPartitionVO> getPartition(int partitionId) {
    return Optional.ofNullable(partitions.get(partitionId));
  }

  public Collection<TopicPartitionVO> getLeaderPartitions(int brokerId) {
    return partitions.values().stream()
        .filter(tp -> tp.getLeader() != null && tp.getLeader().getId() == brokerId)
        .collect(Collectors.toList());
  }

  public Collection<TopicPartitionVO> getUnderReplicatedPartitions() {
    return partitions.values().stream()
        .filter(TopicPartitionVO::isUnderReplicated)
        .collect(Collectors.toList());
  }

  /**
   * Returns the total number of messages published to the topic, ever
   * @return
   */
  public long getTotalSize() {
    return partitions.values().stream()
        .map(TopicPartitionVO::getSize)
        .reduce(0L, Long::sum);
  }

  /**
   * Returns the total number of messages available to consume from the topic.
   * @return
   */
  public long getAvailableSize() {
    return partitions.values().stream()
        .map(p -> p.getSize() - p.getFirstOffset())
        .reduce(0L, Long::sum);
  }

  public double getPreferredReplicaPercent() {
    if (partitions.isEmpty()) {
      return 0;
    } else {
      final var preferredLeaderCount = partitions.values().stream()
          .filter(TopicPartitionVO::isLeaderPreferred)
          .count();
      return ((double) preferredLeaderCount) / ((double) partitions.size());
    }
  }

  @Override
  public int compareTo(TopicVO that) {
    return this.name.compareTo(that.name);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    } else if (o instanceof TopicVO) {
      final var that = (TopicVO) o;
      return Objects.equals(name, that.name);
    } else {
      return false;
    }
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(name);
  }

  @Override
  public String toString() {
    return TopicVO.class.getSimpleName() + " [name=" + name +", partitions=" + partitions + "]";
  }
}

src/main/resources/templates/acl-overview.ftl
<#--
 Copyright 2016 Kafdrop contributors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "/spring.ftl" as spring />
<#import "lib/template.ftl" as template>
<@template.header "ACLs">
    <style type="text/css">
        .bs-table.overview td {
            white-space: nowrap;
        }

        td.leader-partitions {
            word-break: break-all;
        }
    </style>
</@template.header>

<script src="<@spring.url '/js/powerFilter.js'/>"></script>

<#setting number_format="0">

<h2>ACLs</h2>
<div id="searchFilter">Search filter&nbsp;&nbsp;<INPUT id='filter' size=30 NAME='searchRow' title='Just type to filter the rows'></div>
<br/>
<div id="acl-overview">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th><i class="fa fa-tag"></i>&nbsp;&nbsp;Pattern Name</th>
            <th><i class="fa fa-user"></i>&nbsp;&nbsp;Principal</th>
            <th><i class="fa fa-user"></i>&nbsp;&nbsp;Resource Type</th>
            <th><i class="fa fa-tag"></i>&nbsp;&nbsp;Pattern Type</th>
            <th><i class="fa fa-tag"></i>&nbsp;&nbsp;Operation</th>
            <th><i class="fa fa-server"></i>&nbsp;&nbsp;Host</th>
            <th><i class="fa fa-tag"></i>&nbsp;&nbsp;Permission Type</th>
        </tr>
        </thead>
        <tbody>
        <#list acls as a>
            <tr class="dataRow">
                <td>${a.name}</td>
                <td>${a.principal}</td>
                <td>${a.resourceType}</td>
                <td>${a.patternType}</td>
                <td>${a.operation}</td>
                <td>${a.host}</td>
                <td>${a.permissionType}</td>
            </tr>
        </#list>
        </tbody>
    </table>
</div>

<@template.footer/>

src/main/resources/templates/broker-detail.ftl
<#--
 Copyright 2016 Kafdrop contributors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "/spring.ftl" as spring />
<#import "lib/template.ftl" as template>
<@template.header "Broker: ${broker.id?string}">
    <style type="text/css">
        .bs-table.overview td {
            white-space: nowrap;
        }

        td.leader-partitions {
            word-break: break-all;
        }
    </style>
</@template.header>

<#setting number_format="0">

<h2>Broker ID: ${broker.id}</h2>

<div id="topic-overview">
    <h3>Broker Overview</h3>

    <table class="table table-bordered overview">
        <tbody>
        <tr>
            <td><i class="fa fa-laptop"></i>&nbsp;&nbsp;Host</td>
            <td>${broker.host?if_exists}</td>
        </tr>
        <tr>
            <td><i class="fa fa-plug"></i>&nbsp;&nbsp;Port</td>
            <td>${broker.port}</td>
        </tr>
        <tr>
            <td><i class="fa fa-server"></i>&nbsp;&nbsp;Rack</td>
            <td><#if broker.rack??>${broker.rack}<#else>-</#if></td>
        </tr>
        <tr>
            <td><i class="fa fa-trophy"></i>&nbsp;&nbsp;Controller</td>
            <td><@template.yn broker.controller/></td>
        </tr>
        <tr>
            <td><i class="fa fa-database"></i>&nbsp;&nbsp;Number of topics</td>
            <td>${topics?size}</td>
        </tr>

        <#assign partitionCount=0>
        <#list topics as t>
            <#assign partitionCount=partitionCount+(t.getLeaderPartitions(broker.id)?size)>
        </#list>
        <tr>
            <td><i class="fa fa-pie-chart"></i>&nbsp;&nbsp;Number of partitions</td>
            <td>${partitionCount}</td>
        </tr>
        </tbody>
    </table>
</div>

<div>
    <h3>Topic Detail</h3>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Topic</th>
            <th>Total Partitions</th>
            <th>Broker Partitions</th>
            <th>Partition IDs</th>
        </tr>
        </thead>
        <tbody>
        <#list topics as t>
            <tr>
                <td><a href="<@spring.url '/topic/${t.name}'/>">${t.name}</a></td>
                <td>${t.partitions?size}</td>
                <td>${t.getLeaderPartitions(broker.id)?size}</td>
                <td class="leader-partitions"><#list t.getLeaderPartitions(broker.id) as p>${p.id}<#sep>,</#list></td>
            </tr>
        </#list>
        </tbody>
    </table>
</div>

<@template.footer/>

src/main/resources/templates/consumer-detail.ftl
<#--
 Copyright 2016 Kafdrop contributors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "/spring.ftl" as spring />
<#import "lib/template.ftl" as template>
<@template.header "Consumer: ${consumer.groupId}"/>

<#setting number_format="0">

<h2>Kafka Consumer: ${consumer.groupId}</h2>

<div class="container-fluid pl-0">
    <div id="overview">
        <h3>Overview</h3>
        <table class="table table-bordered overview">
            <tbody>
            <tr>
                <td>Topics</td>
                <td>${consumer.topics?size}</td>
            </tr>
            </tbody>
        </table>
    </div>

    <div id="topics">
        <#list consumer.topics as consumerTopic>
            <#assign tableId='topic-${consumerTopic_index}-table'>
            <h3><@template.toggleLink target="#${tableId}" anchor='${tableId}' /> Topic: <a
                        href="<@spring.url '/topic/${consumerTopic.topic}'/>">${consumerTopic.topic}</a></h3>
            <div id="${tableId}">
                <p>
                <table class="table table-bordered table-sm">
                    <thead>
                    <tr>
                        <th>Partition</th>
                        <th>First Offset</th>
                        <th>Last Offset</th>
                        <th>Consumer Offset</th>
                        <th>Lag</th>
                    </tr>
                    </thead>
                    <tbody>
                    <#list consumerTopic.partitions as p>
                        <tr>
                            <td>${p.partitionId}</td>
                            <td>${p.firstOffset}</td>
                            <td>${p.size}</td>
                            <td>${p.offset}</td>
                            <td>${p.lag}</td>
                        </tr>
                    </#list>
                    <tr>
                        <td colspan="4"><b>Combined lag</b></td>
                        <td><b>${consumerTopic.lag}</b></td>
                    </tr>
                    </tbody>
                </table>
                </p>
            </div>
        </#list>
    </div>
</div>

<@template.footer/>

src/main/resources/templates/error.ftl
<#import "/spring.ftl" as spring />
<#import "lib/template.ftl" as template>
<@template.header "${error.error}"/>
<h2>${error.error}</h2>
<div id="errorHeader">
A ${error.status} error has occurred: <span id="errorMessage">${error.message}</span>
</div>
<#if error.trace??>
    <div id="stackTraceTitle">Stack trace</div>
    <div id="stackTrace">
    ${error.trace}
    </div>
<#else>
</#if>
<@template.footer/>

src/main/resources/templates/message-inspector.ftl
<#ftl output_format="HTML">
<#--
 Copyright 2016 Kafdrop contributors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "/spring.ftl" as spring />
<#import "lib/template.ftl" as template>
<@template.header "Topic: ${topic.name}: Messages">
    <style type="text/css">
        h2 {
            margin-bottom: 16px;
        }

        #messageFormPanel {
            margin-top: 16px;
        }

        #partitionSizes {
            margin-left: 16px;
        }

        .badge {
            margin-right: 5px;
        }

        .toggle-msg {
            float: left;
        }
    </style>

    <script src="<@spring.url '/js/message-inspector.js'/>"></script>
    
    <script type="text/javascript">
	$( document ).ready(updateProtobufPanel);
	function updateProtobufPanel()   
	{   	   
	   if ($("#format").val() != "PROTOBUF")
	    {
	        $('#protobufDescriptor').hide();
	        $('#protobufMsgType').hide();
	    }
	    else
	    {
	    	$('#protobufDescriptor').show();
	        $('#protobufMsgType').show();
	    }
	}  
	$(document).ready(function(){
	    $("#format").change(function() {
	    	updateProtobufPanel();
	    });
	});
	</script>
</@template.header>
<#setting number_format="0">


<h2>Topic Messages: <a href="<@spring.url '/topic/${topic.name}'/>">${topic.name}</a></h2>

<#assign selectedPartition=messageForm.partition!0?number>
<#assign selectedFormat=messageForm.format!defaultFormat>

<div id="partitionSizes">
    <#assign curPartition=topic.getPartition(selectedPartition).get()>
    <span class="badge badge-light">First Offset:</span> <span id="firstOffset">${curPartition.firstOffset}</span>&nbsp;
    <span class="badge badge-light">Last Offset:</span> <span id="lastOffset">${curPartition.size}</span>&nbsp;
    <span class="badge badge-light">Size:</span> <span
            id="partitionSize">${curPartition.size - curPartition.firstOffset}</span>
</div>

<div id="messageFormPanel" class="card">
    <form method="GET" action="<@spring.url '/topic/${topic.name}/messages'/>" id="messageForm" class="form-inline card-body">
        <div class="form-group">
            <label for="partition">Partition</label>
            <select class="form-control" id="partition" name="partition">
                <#list topic.partitions as p>
                    <option value="${p.id}" data-first-offset="${p.firstOffset}" data-last-offset="${p.size}"
                            <#if p.id == selectedPartition>selected="selected"</#if>>${p.id}</option>
                </#list>
            </select>
        </div>
        &nbsp;&nbsp;
        <@spring.bind path="messageForm.offset"/>
        <div class="form-group ${spring.status.error?string("has-error", "")}">
            <label class="control-label" for="offset">Offset</label>
            <@spring.formInput path="messageForm.offset" attributes='class="form-control"'/>
            <#if spring.status.error>
                <span class="text-danger"><i class="fa fa-times-circle"></i><@spring.showErrors "<br/>"/></span>
            </#if>
        </div>
        &nbsp;&nbsp;
        <@spring.bind path="messageForm.count"/>
        <div class="form-group ${spring.status.error?string("has-error", "")}">
            <label class=control-label" for="count"># messages</label>
            <@spring.formInput path="messageForm.count" attributes='class="form-control ${spring.status.error?string("has-error", "")}"'/>
            <#if spring.status.error>
                <span class="text-danger"><i class="fa fa-times-circle"></i><@spring.showErrors "<br/>"/></span>
            </#if>
        </div>
        &nbsp;&nbsp;
        <div class="form-group">
            <label for="format">Message format</label>
            <select class="form-control" id="format" name="format">
                <#list messageFormats as f>
                    <option value="${f}" <#if f == selectedFormat>selected="selected"</#if>>${f}</option>
                </#list>
            </select>
        </div>
        &nbsp;&nbsp;        
        <div class="form-group" id="protobufDescriptor">
            <label for="format">Protobuf descriptor</label>
            <select class="form-control" id="descFile" name="descFile">
                <#list descFiles as f>
                    <option value="${f}">${f}</option>
                </#list>
            </select>
        </div>
        &nbsp;&nbsp;
        <div class="form-group" id="protobufMsgType">
            <label class=control-label" for="format">Protobuf message type name</label>
            <@spring.formInput path="messageForm.msgTypeName" attributes='class="form-control"'/>
        </div>
        &nbsp;&nbsp;  

        <button class="btn btn-success" type="submit"><i class="fa fa-search"></i> View Messages</button>
    </form>
</div>

<@spring.bind path="messageForm.*"/>
<div id="message-display" class="container">
    <#if messages?? && messages?size gt 0>
        <#list messages as msg>
            <div class="message-detail">
                <span class="badge badge-light">Offset:</span> ${msg.offset} &nbsp;
                <span class="badge badge-light">Key:</span> ${msg.key!''} &nbsp;
                <span class="badge badge-light">Timestamp:</span> ${msg.timestamp?string('yyyy-MM-dd HH:mm:ss.SSS')}
                <span class="badge badge-light">Headers:</span> ${msg.headersFormatted}
                <div>
                    <a href="#" class="toggle-msg"><i class="fa fa-chevron-circle-right">&nbsp;</i></a>
                    <pre class="message-body">${msg.message!''}</pre>
                </div>
            </div>
        </#list>
    <#elseif !(spring.status.error) && !(messageForm.empty)>
        No messages found in partition ${(messageForm.partition)!"PARTITION_NOT_SET"} at offset ${messageForm.offset}
    </#if>
</div>

<@template.footer/>

src/main/resources/templates/not-initialized.ftl
<#--
 Copyright 2016 Kafdrop contributors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "lib/template.ftl" as template>
<@template.header "Initializing...">
    <meta http-equiv="refresh" content="5">
</@template.header>

<div>
    <p>Internal caches are still initializing. Please wait...</p>
</div>

<@template.footer/>

src/main/resources/templates/topic-detail.ftl
<#--
 Copyright 2016 Kafdrop contributors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "/spring.ftl" as spring />
<#import "lib/template.ftl" as template>
<@template.header "Topic: ${topic.name}">
    <style type="text/css">
        #action-bar {
            margin-top: 17px;
        }

        th {
            word-break: break-all;
        }
    </style>
</@template.header>

<#setting number_format="0">

<h2>Topic: ${topic.name}</h2>

<div id="action-bar" class="container pl-0">
  <a id="topic-messages" class="btn btn-outline-light" href="<@spring.url '/topic/${topic.name}/messages'/>"><i class="fa fa-eye"></i> View Messages</a>
</div>
<br/>
<div class="container-fluid pl-0">
    <div class="row">
        <div id="topic-overview" class="col-md-8">
            <h3>Overview</h3>

            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td># of partitions</td>
                    <td>${topic.partitions?size}</td>
                </tr>
                <tr>
                    <td>Preferred replicas</td>
                    <td <#if topic.preferredReplicaPercent lt 1.0>class="warning"</#if>>${topic.preferredReplicaPercent?string.percent}</td>
                </tr>
                <tr>
                    <td>Under-replicated partitions</td>
                    <td <#if topic.underReplicatedPartitions?size gt 0>class="warning"</#if>>${topic.underReplicatedPartitions?size}</td>
                </tr>
                <tr>
                    <td>Total size</td>
                    <td>${topic.totalSize}</td>
                </tr>
                <tr>
                    <td>Total available messages</td>
                    <td>${topic.availableSize}</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div id="topic-config" class="col-md-4">
            <h3>Configuration</h3>

            <#if topic.config?size == 0>
                <div>No topic-specific configuration</div>
            <#else>
                <table class="table table-bordered">
                    <tbody>
                    <#list topic.config?keys as c>
                        <tr>
                            <td>${c}</td>
                            <td>${topic.config[c]}</td>
                        </tr>
                    </#list>
                    </tbody>
                </table>
            </#if>
        </div>

    </div>

    <div class="row">
        <div id="partition-detail" class="col-md-8">
            <h3>Partition Detail</h3>
            <table id="partition-detail-table" class="table table-bordered table-sm small">
                <thead>
                <tr>
                    <th>Partition</th>
                    <th>First<br>Offset</th>
                    <th>Last<br>Offset</th>
                    <th>Size</th>
                    <th>Leader<br>Node</th>
                    <th>Replica<br>Nodes</th>
                    <th>In-sync<br>Replica<br>Nodes</th>
                    <th>Offline<br>Replica<br>Nodes</th>
                    <th>Preferred<br>Leader</th>
                    <th>Under-replicated</th>
                </tr>
                </thead>
                <tbody>
                <#list topic.partitions as p>
                    <tr>
                        <td><a href="<@spring.url '/topic/${topic.name}/messages?partition=${p.id}&offset=${p.firstOffset}&count=100'/>">${p.id}</a></td>
                        <td>${p.firstOffset}</td>
                        <td>${p.size}</td>
                        <td>${p.size - p.firstOffset}</td>
                        <td <#if !(p.leader)??>class="warning"</#if>>${(p.leader.id)!"none"}</td>
                        <td><#list p.replicas as r>${r.id}<#if r_has_next>,</#if></#list></td>
                        <td><#list p.inSyncReplicas as r>${r.id}<#if r_has_next>,</#if></#list></td>
                        <td><#list p.offlineReplicas as r>${r.id}<#if r_has_next>,</#if></#list></td>
                        <td <#if !p.leaderPreferred>class="warning"</#if>><@template.yn p.leaderPreferred/></td>
                        <td <#if p.underReplicated>class="warning"</#if>><@template.yn p.underReplicated/></td>
                    </tr>
                </#list>
                </tbody>
            </table>
        </div>

        <div id="consumers" class="col-md-4">
            <h3>Consumers</h3>
            <table id="consumers-table" class="table table-bordered table-sm small">
                <thead>
                <tr>
                    <th>Group ID</th>
                    <th>Combined Lag</th>
                </tr>
                </thead>
                <tbody>
                <#list consumers![] as c>
                    <tr>
                        <td><a href="<@spring.url '/consumer/${c.groupId}'/>">${c.groupId}</a></td>
                        <td>${c.getTopic(topic.name).lag}</td>
                    </tr>
                </#list>
                </tbody>
            </table>
        </div>
    </div>
</div>
<@template.footer/>

src/main/resources/templates/topic-messages.ftl
<#--
 Copyright 2019 Kafdrop contributors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<#import "/spring.ftl" as spring />
<#import "lib/template.ftl" as template>

<@template.header "Topic: ${topic.name}: Messages">
    <style type="text/css">
        h2 {
            margin-bottom: 16px;
        }
        .badge {
            margin-right: 5px;
        }
        .toggle-msg {
            float: left;
        }
    </style>
    <script src="<@spring.url '/js/message-inspector.js'/>"></script>
</@template.header>
<#setting number_format="0">

<h2>Topic Messages: <a href="<@spring.url '/topic/${topic.name}'/>">${topic.name}</a></h2>

<div class="container">
    <#if messages?? && messages?size gt 0>
        <#list messages as msg>
            <div class="message-detail">
                <span class="badge badge-light">Partition:</span> ${msg.partition} &nbsp;
                <span class="badge badge-light">Offset:</span> ${msg.offset} &nbsp;
                <span class="badge badge-light">Key:</span> ${msg.key!''} &nbsp;
                <span class="badge badge-light">Timestamp:</span> ${msg.timestamp?string('yyyy-MM-dd HH:mm:ss.SSS')}
                <span class="badge badge-light">Headers:</span> ${msg.headersFormatted}
                <div>
                    <a href="#" class="toggle-msg"><i class="fa fa-chevron-circle-right">&nbsp;</i></a>
                    <pre class="message-body">${msg.message!''}</pre>
                </div>
            </div>
        </#list>

    </#if>
</div>

<@template.footer/>